# =========================
# PROFILE: PROD (RENDER)
# =========================

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=validate

# Flyway ligado para criar tabela e popular dados iniciais
spring.flyway.enabled=true

# H2 console desligado em produção
spring.h2.console.enabled=false

server.port=${PORT:8080}